# Naive RAG vs CRAG on the same 50 HotpotQA questions

This tutorial compares a controlled naive-RAG baseline with the corrective pipeline described by Shi-Qi Yan, Jia-Chen Gu, Yun Zhu, and Zhen-Hua Ling in [*Corrective Retrieval Augmented Generation*, arXiv:2401.15884](https://arxiv.org/abs/2401.15884).

## Learning goals

By the end, you can identify what the comparison holds constant, separate string metrics from human answer quality, inspect paired failures, and judge whether correction helped on this 50-question slice.

## Fairness contract

Both methods receive the same question and identical ranked top-3 passages from the question's HotpotQA distractor pool. Both use `agnes-3.0-flash` and the same evidence-only answer generator. Naive RAG sends all complete passages directly to generation. CRAG evaluates, routes, selects exact sentence strips, and then generates. Web search is disabled. Gold answers and gold labels never enter model prompts.

The setup isolates the corrective stages. It does not reproduce the paper's trained T5-large evaluator or establish general accuracy. Human judgements cover all 50 pairs and are tied to exact answer/evidence fingerprints.

### Set up the reproducible environment

**Motivation.** Use the same repo paths, credentials, and fixed model as the main course.

**Paper mapping.** Infrastructure needed for the comparison.

**Next cell.** Resolve the repo root, import the comparison APIs, and verify credential presence without printing values.

**Failure signals.** Missing variables, a wrong kernel, or imports from another checkout stop execution before model calls.

**Read the output.** Both flags should be True and the model must be agnes-3.0-flash.

In [1]:
import json
import sys
from collections import Counter
from pathlib import Path
import pandas as pd
from IPython.display import display, Markdown

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from src.config import check_environment, MODEL_NAME
from src.data_hotpot import build_slice
from src.qdrant_store import index_slice, close_qdrant_client
from src.retrieve import search
from src.pipeline import run_crag
from src.comparison import run_naive_rag, run_comparison_50, automated_metrics, load_manual_reviews

env = check_environment()
print(env)
assert all(env.values()) and MODEL_NAME == "agnes-3.0-flash"

{'AGNESAI_API_KEY': True, 'HF_TOKEN': True}

### Load the exact course slice and index

**Motivation.** A paired comparison needs the same questions and corpus for both methods.

**Paper mapping.** The paper motivates correction after retrieval. This adaptation uses HotpotQA.

**Next cell.** Load the seed-42 slice, index it idempotently, and lock the first 50 IDs.

**Failure signals.** A dataset provenance mismatch rebuilds the slice; a Qdrant lock means another kernel owns the store.

**Read the output.** Expect 200 records, 50 unique comparison IDs, and 1,992 indexed paragraphs.

In [2]:
records, _ = build_slice(n=200, seed=42)
indexed = index_slice(records)
comparison_ids = [row["id"] for row in records[:50]]
assert len(records) == 200 and len(set(comparison_ids)) == 50
print("Indexed paragraphs:", indexed)
print("Comparison IDs:", len(comparison_ids), comparison_ids[:3], "...", comparison_ids[-1])

[*] Collection 'hotpot_slice' already indexed with 1992 points. Skipping upsert.
Indexed paragraphs: 1992
Comparison IDs: 50 ['5add1d575542992c1e3a2540', '5ac55ea55542993e66e82377', '5ac3a76e554299741d48a2be'] ... 5ac0e064554299012d1db64e

## What “naive” means here

Naive RAG is retrieval → generation. It does not inspect relevance scores, choose Correct/Incorrect/Ambiguous, filter sentences, or search the web. It still uses a grounded answer prompt so both methods follow the same evidence rule. The baseline context is the full text of all three retrieved passages in rank order.

### Verify one shared retrieval set

**Motivation.** Check the experimental control before comparing answers.

**Paper mapping.** Both branches begin from the same retriever output; only the corrective stages differ.

**Next cell.** Retrieve the first question once and display its ranked titles, similarities, and diagnostic gold labels.

**Failure signals.** Different question IDs in payloads indicate a broken pool filter; similarity is not relevance confidence.

**Read the output.** The same three objects shown here are passed to both methods.

In [3]:
worked = records[0]
worked_hits = search(worked["question"], k=3, question_id=worked["id"])
assert all(hit["payload"]["question_id"] == worked["id"] for hit in worked_hits)
display(pd.DataFrame([{"rank": i + 1, "title": hit["title"], "similarity": hit["score"], "is_gold": hit["payload"]["is_gold"]} for i, hit in enumerate(worked_hits)]))

   rank               title  similarity  is_gold
0     1  Royal Flash (film)    0.893053     True
1     2         Royal Flash    0.812065    False
2     3      Harry Flashman    0.801413    False

### Run naive RAG on complete passages

**Motivation.** Establish the baseline answer without evaluator or refinement calls.

**Paper mapping.** This is the uncorrected retrieval-to-generation path that CRAG is intended to improve.

**Next cell.** Pass the three complete retrieved texts directly to the grounded generator.

**Failure signals.** An abstention means the generator found the full retrieved context insufficient; it is not a transport failure.

**Read the output.** Inspect the answer and the exact titles supplied to it; gold labels were not included in the prompt.

In [4]:
worked_naive = run_naive_rag(worked["question"], worked_hits)
print("Question:", worked["question"])
print("Evidence titles:", worked_naive["evidence_titles"])
print("Naive answer:", worked_naive["answer"])
print("Actual requests:", worked_naive["n_llm_calls"])

Question: What nationality was Oliver Reed's character in the film Royal Flash?
Evidence titles: ['Royal Flash (film)', 'Royal Flash', 'Harry Flashman']
Naive answer: I don't have enough information in the provided evidence to answer this question.
Actual requests: 0

### Run CRAG on those identical passages

**Motivation.** Observe the effect of evaluation, routing, and strip refinement without changing retrieval.

**Paper mapping.** Maps directly to the paper's corrective control flow, implemented here with a prompted Agnes evaluator.

**Next cell.** Pass the already-retrieved hit objects into CRAG and display its decision and retained strips.

**Failure signals.** A Correct action does not prove both hops are present; an empty strip set leads to a safe abstention.

**Read the output.** Compare the retained evidence with the full naive context before comparing answer text.

In [5]:
worked_crag = run_crag(worked["question"], worked["id"], k=3, allow_web=False, docs=worked_hits)
print("Action:", worked_crag.action)
display(pd.DataFrame([{k: item[k] for k in ("title", "score", "label", "why")} for item in worked_crag.evaluations]))
print("Kept strips:", json.dumps(worked_crag.strips, indent=2, ensure_ascii=False))
print("CRAG answer:", worked_crag.answer)
print("Gold answer:", worked["gold_answer"])

Action: Correct

,title,score,label,why
0,Royal Flash (film),1.0,relevant,The evidence confirms Oliver Reed played Otto ...
1,Royal Flash,0.0,irrelevant,The evidence identifies the film and its sourc...
2,Harry Flashman,0.2,irrelevant,The evidence identifies the actor as Malcolm M...

Kept strips: [
  "Additionally, Oliver Reed appeared in the role of Otto von Bismarck, Alan Bates as Rudi von Sternberg, and Florinda Bolkan played Lola Montez."
]
CRAG answer: I don't have enough information in the provided evidence to answer this question.
Gold answer: Prussian

## Paired 50-question run

Each ID is atomically checkpointed, so a crash resumes at the failed ID. A first run can make one naive generation request plus CRAG evaluator, refinement, and generation requests per row; primitive CRAG caches can reduce that count. A warm rerun reports zero new calls. It does not erase the requests that created the cache.

### Execute all 50 paired questions

**Motivation.** Collect enough paired cases to see systematic wins, losses, abstentions, and metric disagreements.

**Paper mapping.** A tutorial comparison of the paper-inspired correction mechanism, not the paper benchmark.

**Next cell.** Run both methods on the same 50 questions with k=3 and web disabled.

**Failure signals.** Provider/schema failures are checkpointed and retried; exhausted retries stop without dropping the row.

**Read the output.** Every progress line identifies cache state and actual requests for that comparison invocation.

In [6]:
rows = run_comparison_50(records, k=3, allow_web=False)
assert len(rows) == 50 and [row["id"] for row in rows] == comparison_ids
print("Completed paired rows:", len(rows))

comparison: 1/50; cached=True; requests=0

comparison: 2/50; cached=True; requests=0

comparison: 3/50; cached=True; requests=0

comparison: 4/50; cached=True; requests=0

comparison: 5/50; cached=True; requests=0

comparison: 6/50; cached=True; requests=0

comparison: 7/50; cached=True; requests=0

comparison: 8/50; cached=True; requests=0

comparison: 9/50; cached=True; requests=0

comparison: 10/50; cached=True; requests=0

comparison: 11/50; cached=True; requests=0

comparison: 12/50; cached=True; requests=0

comparison: 13/50; cached=True; requests=0

comparison: 14/50; cached=True; requests=0

comparison: 15/50; cached=True; requests=0

comparison: 16/50; cached=True; requests=0

comparison: 17/50; cached=True; requests=0

comparison: 18/50; cached=True; requests=0

comparison: 19/50; cached=True; requests=0

comparison: 20/50; cached=True; requests=0

comparison: 21/50; cached=True; requests=0

comparison: 22/50; cached=True; requests=0

comparison: 23/50; cached=True; requests=0

comparison: 24/50; cached=True; requests=0

comparison: 25/50; cached=True; requests=0

comparison: 26/50; cached=True; requests=0

comparison: 27/50; cached=True; requests=0

comparison: 28/50; cached=True; requests=0

comparison: 29/50; cached=True; requests=0

comparison: 30/50; cached=True; requests=0

comparison: 31/50; cached=True; requests=0

comparison: 32/50; cached=True; requests=0

comparison: 33/50; cached=True; requests=0

comparison: 34/50; cached=True; requests=0

comparison: 35/50; cached=True; requests=0

comparison: 36/50; cached=True; requests=0

comparison: 37/50; cached=True; requests=0

comparison: 38/50; cached=True; requests=0

comparison: 39/50; cached=True; requests=0

comparison: 40/50; cached=True; requests=0

comparison: 41/50; cached=True; requests=0

comparison: 42/50; cached=True; requests=0

comparison: 43/50; cached=True; requests=0

comparison: 44/50; cached=True; requests=0

comparison: 45/50; cached=True; requests=0

comparison: 46/50; cached=True; requests=0

comparison: 47/50; cached=True; requests=0

comparison: 48/50; cached=True; requests=0

comparison: 49/50; cached=True; requests=0

comparison: 50/50; cached=True; requests=0

Completed paired rows: 50

### Compare automated proxies

**Motivation.** Quantify retrieval coverage, string overlap, abstention, and current-run cost before human interpretation.

**Paper mapping.** These diagnostics are tutorial additions; they are not the paper's reported results.

**Next cell.** Compute paired metrics and a compact per-method table.

**Failure signals.** Substring match can reward negation or miss aliases; it must not be called accuracy.

**Read the output.** Look for different answer behavior despite identical title recall, then check whether this invocation was cold or cached.

In [7]:
auto = automated_metrics(rows)
print(json.dumps(auto, indent=2))
display(pd.DataFrame({
    "method": ["Naive RAG", "CRAG"],
    "substring_match": [auto["naive_substring_match"], auto["crag_substring_match"]],
    "abstention_rate": [auto["naive_abstention_rate"], auto["crag_abstention_rate"]],
    "actual_requests_this_run": [auto["naive_llm_calls"], auto["crag_llm_calls"]],
}))

{
  "n_questions": 50,
  "gold_title_recall@3": 0.42,
  "naive_substring_match": 0.3,
  "crag_substring_match": 0.26,
  "naive_abstention_rate": 0.66,
  "crag_abstention_rate": 0.72,
  "naive_llm_calls": 0,
  "crag_llm_calls": 0,
  "cached_rows": 50
}

      method  substring_match  abstention_rate  actual_requests_this_run
0  Naive RAG             0.30             0.66                         0
1       CRAG             0.26             0.72                         0

## Human audit of all 50 pairs

All 50 pairs were reviewed manually against the question, reference answer, and evidence given to each method. The audit is method-aware: the reviewer could see which answer came from naive RAG and which came from CRAG. That supports pipeline-specific error attribution and can introduce reviewer bias, which remains a limitation.

Correctness labels are `correct`, `partially_correct`, `incorrect`, and `abstain`. Evidence labels are `fully_supported`, `partially_supported`, `unsupported`, and `no_answer`. Pairwise preference weighs semantic correctness first, then evidence support, appropriate abstention, and concision or contradiction. A safe abstention is preferred to an unsupported wrong answer. Reviews are human judgements, not additional Agnes calls.

### Validate reviews against exact outputs

**Motivation.** Prevent a judgement from silently attaching to a regenerated answer or changed evidence set.

**Paper mapping.** Manual evaluation supplements automated metrics; it is not part of the CRAG algorithm.

**Next cell.** Load the tracked 50-row audit and compare its fingerprints with this run.

**Failure signals.** Missing or changed rows are listed for re-review while the notebook remains runnable.

**Read the output.** A fully reviewed run shows 50 valid and zero stale IDs.

In [8]:
review_path = ROOT / "reviews/naive_vs_crag_50_manual.json"
reviews, stale_ids = load_manual_reviews(rows, review_path)
print("Valid manual reviews:", len(reviews))
print("Stale or missing IDs:", stale_ids)

Valid manual reviews: 50
Stale or missing IDs: []

### Summarize human answer quality

**Motivation.** Use semantic and evidence judgements alongside the string heuristic.

**Paper mapping.** This is an external tutorial audit of the two pipelines. It is not a trained evaluator or paper metric.

**Next cell.** Count correctness, grounding, and pairwise preferences for all fingerprint-valid reviews.

**Failure signals.** If fewer than 50 reviews validate, totals are incomplete and no overall winner should be claimed.

**Read the output.** Compare method correctness with preference counts and note ties; the sample remains descriptive.

In [9]:
if len(reviews) == 50:
    manual_summary = {
        "naive_correctness": dict(Counter(r["naive_correctness"] for r in reviews)),
        "crag_correctness": dict(Counter(r["crag_correctness"] for r in reviews)),
        "naive_support": dict(Counter(r["naive_support"] for r in reviews)),
        "crag_support": dict(Counter(r["crag_support"] for r in reviews)),
        "preference": dict(Counter(r["preference"] for r in reviews)),
    }
    print(json.dumps(manual_summary, indent=2))
else:
    manual_summary = {}
    print("Manual summary withheld until all 50 exact outputs are reviewed.")

{
  "naive_correctness": {
    "abstain": 33,
    "correct": 15,
    "incorrect": 1,
    "partially_correct": 1
  },
  "crag_correctness": {
    "abstain": 36,
    "correct": 13,
    "incorrect": 1
  },
  "naive_support": {
    "no_answer": 33,
    "fully_supported": 15,
    "partially_supported": 2
  },
  "crag_support": {
    "no_answer": 36,
    "fully_supported": 12,
    "partially_supported": 2
  },
  "preference": {
    "tie_both_inadequate": 33,
    "tie_both_good": 11,
    "naive_better": 4,
    "crag_better": 2
  }
}

### Find string-metric disagreements

**Motivation.** Show why literal answer overlap cannot replace human inspection.

**Paper mapping.** The paper motivates stronger correction; this cell critiques our tutorial evaluation proxy.

**Next cell.** Join reviews to outputs and display cases where substring match disagrees with manual correctness.

**Failure signals.** An empty table means agreement on this run, not proof that substring matching is generally valid.

**Read the output.** Alias misses and incidental matches should be visible with their human rationale.

In [10]:
review_by_id = {review["id"]: review for review in reviews}
disagreements = []
for row in rows:
    review = review_by_id.get(row["id"])
    if not review:
        continue
    for method in ("naive", "crag"):
        manually_correct = review[f"{method}_correctness"] == "correct"
        substring = row[method]["answer_contains_gold"]
        if manually_correct != substring:
            disagreements.append({"id": row["id"], "method": method, "question": row["question"],
                                  "gold": row["gold_answer"], "answer": row[method]["answer"],
                                  "substring": substring, "manual": review[f"{method}_correctness"],
                                  "why": review["rationale"]})
display(pd.DataFrame(disagreements))
print("Metric disagreements:", len(disagreements))

,id,method,question,gold,answer,substring,manual,why
0,5ac55ea55542993e66e82377,naive,Pacific Mozart Ensemble performed which German...,Kurt Julian Weill,Kurt Weill,False,correct,Both correctly answer Kurt Weill from explicit...
1,5ac55ea55542993e66e82377,crag,Pacific Mozart Ensemble performed which German...,Kurt Julian Weill,Kurt Weill,False,correct,Both correctly answer Kurt Weill from explicit...
2,5ac15de55542991316484afb,naive,Were the films Crazy Love and Welcome to Nolly...,no,I don't have enough information in the provide...,True,abstain,The retrieved items are unrelated to the two f...
3,5ac15de55542991316484afb,crag,Were the films Crazy Love and Welcome to Nolly...,no,I don't have enough information in the provide...,True,abstain,The retrieved items are unrelated to the two f...
4,5a81537355429926c1cdad20,naive,What conference champions were putted against ...,Eastern Conference champion Orlando Magic agai...,The first NBA Finals in which the Orlando Magi...,False,correct,Naive RAG gives the exact 1995 conference cham...
5,5abe6f8455429965af743f03,naive,What country of origin does Robert brothers an...,French,France,False,correct,"Both answer France, which is semantically equi..."
6,5abe6f8455429965af743f03,crag,What country of origin does Robert brothers an...,French,France,False,correct,"Both answer France, which is semantically equi..."
7,5a72688c5542997f827839b2,naive,The Atik Valide Mosque and Valens Aqueduct are...,Turkey,"The Atik Valide Mosque is located in Istanbul,...",True,partially_correct,"Both name Turkey, but only the Atik Valide Mos..."
8,5adea0c5554299728e26c776,naive,Are both Helen Dunmore and M. P. Shiel of West...,no,I don't have enough information in the provide...,True,abstain,"Helen Dunmore is described as British, but M. ..."
9,5adea0c5554299728e26c776,crag,Are both Helen Dunmore and M. P. Shiel of West...,no,I don't have enough information in the provide...,True,abstain,"Helen Dunmore is described as British, but M. ..."

Metric disagreements: 10

## Exercise

Pick one `naive_better`, one `crag_better`, and one inadequate tie. For each, trace retrieval → supplied evidence → answer. Decide whether retrieval, CRAG evaluation, refinement, or generation caused the result. The next cell provides a compact scaffold from the completed human audit.

### Build a three-case error-analysis scaffold

**Motivation.** Practice causal diagnosis alongside win counts.

**Paper mapping.** CRAG's components create identifiable failure boundaries after shared retrieval.

**Next cell.** Select one reviewed example from each requested preference category and expose its evidence path.

**Failure signals.** A missing category is reported honestly; the notebook does not substitute an unrelated example.

**Read the output.** Use the shown action, titles, strips, and rationale to explain where the methods diverged.

In [11]:
for preference in ("naive_better", "crag_better", "tie_both_inadequate"):
    chosen = next((review for review in reviews if review["preference"] == preference), None)
    print("\n", preference.upper())
    if not chosen:
        print("No reviewed row in this category.")
        continue
    row = next(item for item in rows if item["id"] == chosen["id"])
    print("Q:", row["question"])
    print("Retrieved:", [hit["title"] for hit in row["hits"]])
    print("CRAG action/kept:", row["crag"]["action"], row["crag"]["kept_titles"])
    print("Diagnosis:", chosen["error_types"], "—", chosen["rationale"])

 NAIVE_BETTER
Q: After his curacy at the village that is a suburb of Scunthorpe, who was Industrial Chaplain to the Bishop of Lincoln?
Retrieved: ['William Everingham', 'Ernest Holmes (priest)', 'Bill Dudman']
CRAG action/kept: Correct ['Bill Dudman']
Diagnosis: ['generation_error'] — The full Bill Dudman passage directly supports the naive answer; CRAG retains the decisive chaplain sentence but still abstains.

 CRAG_BETTER
Q: What is the first two words of the fifth studio album of Joseph Edgar Foreman?
Retrieved: ['The Hungry Hustlerz: Starvation Is Motivation', 'Como Ama una Mujer', 'Too Much Stereo']
CRAG action/kept: Correct ['The Hungry Hustlerz: Starvation Is Motivation']
Diagnosis: ['generation_error'] — The album title is explicit; CRAG returns its first two words while naive RAG abstains despite receiving the same decisive passage.

 TIE_BOTH_INADEQUATE
Q: What nationality was Oliver Reed's character in the film Royal Flash?
Retrieved: ['Royal Flash (film)', 'Royal Flash', 'Harry Flashman']
CRAG action/kept: Correct ['Royal Flash (film)']
Diagnosis: ['retrieval_gap', 'appropriate_abstention'] — The passages identify Oliver Reed as Bismarck but never state that the character was Prussian, so neither method answers and both abstentions are evidence-aware.

### Release Qdrant before the final report

**Motivation.** Avoid a Windows file lock after all retrieval-dependent work is complete.

**Paper mapping.** Operational cleanup is outside the comparison algorithm.

**Next cell.** Close the shared embedded client; the final reporting cell uses in-memory rows only.

**Failure signals.** If another kernel owns the store, shut it down. Do not delete lock files.

**Read the output.** The confirmation means this kernel released its client.

In [12]:
close_qdrant_client()
print("Qdrant client closed.")

Qdrant client closed.

### Final answer-by-answer comparison

**Motivation.** End with the complete human-readable evidence needed to inspect every verdict.

**Paper mapping.** This reporting layer compares the naive baseline with the paper-inspired corrective path.

**Next cell.** Print all 50 questions with gold, naive, CRAG, manual verdict, and rationale in slice order.

**Failure signals.** A NOT REVIEWED verdict means the answer/evidence fingerprint changed and requires a new human judgement.

**Read the output.** Read each block as a paired case; aggregate claims must agree with these 50 underlying decisions.

In [13]:
for number, row in enumerate(rows, 1):
    review = review_by_id.get(row["id"])
    verdict = review["preference"] if review else "NOT REVIEWED"
    reason = review["rationale"] if review else "The saved manual review is missing or stale for this exact output."
    print("=" * 100)
    print(f"Q{number:02d} [{row['id']}]: {row['question']}")
    print("Gold answer:", row["gold_answer"])
    print("Naive RAG:", row["naive"]["answer"])
    print("CRAG:", row["crag"]["answer"])
    print("Manual verdict:", verdict)
    print("Why:", reason)

====================================================================================================
Q01 [5add1d575542992c1e3a2540]: What nationality was Oliver Reed's character in the film Royal Flash?
Gold answer: Prussian
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The passages identify Oliver Reed as Bismarck but never state that the character was Prussian, so neither method answers and both abstentions are evidence-aware.
====================================================================================================
Q02 [5ac55ea55542993e66e82377]: Pacific Mozart Ensemble performed which German composer's Der Lindberghflug in 2002?
Gold answer: Kurt Julian Weill
Naive RAG: Kurt Weill
CRAG: Kurt Weill
Manual verdict: tie_both_good
Why: Both correctly answer Kurt Weill from explicit evidence; the longer reference name Kurt Julian Weill makes literal substring matching undercount this valid alias.
====================================================================================================
Q03 [5ac3a76e554299741d48a2be]: Who released the song "With or Without You" first, Jai McDowall or U2?
Gold answer: U2
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The evidence gives Jai McDowall's 2011 release but not U2's earlier release, so the comparison cannot be established from the retrieved text.
====================================================================================================
Q04 [5a7133565542994082a3e65c]: What Kentucky county has a population of 60,316 and features the Lake Louisvilla neighborhood?
Gold answer: Oldham County
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Oldham County appears in the location passage, but the population clue needed to confirm the intended county is absent.
====================================================================================================
Q05 [5ac1a4745542991316484b82]: Para Hills West, South Australia lies within a city with what estimated population?
Gold answer: 138,535
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The passages identify the City of Salisbury but do not provide its estimated population.
====================================================================================================
Q06 [5adc597d55429947ff17392f]: In what year was the narrator of "Blackadder's Christmas Carol" born?
Gold answer: 1959
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The narrator is identified as Hugh Laurie, but his birth year is not present in the retrieved evidence.
====================================================================================================
Q07 [5ac55e835542993e66e82375]: Thomas Fitch defended John Henry Holliday when he was accused of killing men during the gunfight at the o.k. corral, when was that?
Gold answer: October 25, 1881
Naive RAG: The gunfight at the O.K. Corral took place on October 26, 1881.
CRAG: October 26, 1881
Manual verdict: tie_both_inadequate
Why: Both answer October 26, 1881 exactly as the retrieved passage states, but the supplied reference answer is October 25, 1881; this is a reference-versus-evidence conflict.
====================================================================================================
Q08 [5a8d9e0f554299441c6ba015]: The actor that played Gutthi on Comedy nights with Kapil Show also starred in what 2016 Punjabi film directed by Smeep Kang?
Gold answer: Vaisakhi List
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The Vaisakhi List passage explicitly gives the 2016 film, director, and Sunil Grover, yet both methods abstain instead of returning the title.
====================================================================================================
Q09 [5ae70ed7554299572ea546a1]: Victor Varnada directed Twisted Fortune, which starred which brother of Eddie Murphy?
Gold answer: Charlie Murphy
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: None of the retrieved passages mentions Twisted Fortune or Charlie Murphy.
====================================================================================================
Q10 [5a74a8fa55429929fddd8497]: After his curacy at the village that is a suburb of Scunthorpe, who was Industrial Chaplain to the Bishop of Lincoln?
Gold answer: Dudman
Naive RAG: Bill Dudman
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: naive_better
Why: The full Bill Dudman passage directly supports the naive answer; CRAG retains the decisive chaplain sentence but still abstains.
====================================================================================================
Q11 [5a7cb94f554299683c1c6353]: What is the first two words of the fifth studio album of Joseph Edgar Foreman?
Gold answer: The Hungry
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: The Hungry
Manual verdict: crag_better
Why: The album title is explicit; CRAG returns its first two words while naive RAG abstains despite receiving the same decisive passage.
====================================================================================================
Q12 [5ab874ba5542990e739ec904]: The Twelfth United States Army Group commander was the first chairman of what?
Gold answer: Joint Chiefs of Staff
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Retrieval identifies Omar Bradley as commander but omits the passage establishing his chairmanship of the Joint Chiefs of Staff.
====================================================================================================
Q13 [5ae3a8985542992f92d82329]: Politician Lyman Sherwood was born in what New York county?
Gold answer: Rensselaer County
Naive RAG: Rensselaer County
CRAG: Rensselaer County
Manual verdict: tie_both_good
Why: Both return Rensselaer County, which is stated directly in Lyman Sherwood's birthplace line.
====================================================================================================
Q14 [5ac39f7b554299218029dbe7]: Robert Earl Holding owned an oil company that was originally founded by who?
Gold answer: Harry F. Sinclair
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The retrieved oil companies do not connect Robert Earl Holding to the company founded by Harry F. Sinclair.
====================================================================================================
Q15 [5ae27b535542996483e649b6]: The chorus of "On the Radio" contains references to the song "November Rain" whose band's lead singer is?
Gold answer: Axl Rose
Naive RAG: Axl Rose
CRAG: Axl Rose
Manual verdict: tie_both_good
Why: Both correctly identify Axl Rose from the explicit Guns N' Roses lead-singer sentence.
====================================================================================================
Q16 [5a7331de5542994cef4bc4a8]: If the Charhki  Dadri crash was less dangerous than the Tenerife airport disaster, which occured firat?
Gold answer: On March 27, 1977, two Boeing 747 passenger jets, KLM Flight 4805 and Pan Am Flight 1736, collided on the runway at Los Rodeos Airport (now Tenerife North Airport)
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The Tenerife date is present but the Charkhi Dadri date needed for a chronological comparison is absent.
====================================================================================================
Q17 [5ac15de55542991316484afb]: Were the films Crazy Love and Welcome to Nollywood both released in 2008?
Gold answer: no
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The retrieved items are unrelated to the two films, so abstention is appropriate; the gold word 'no' can nevertheless spuriously match text inside an abstention.
====================================================================================================
Q18 [5a7c6c9d554299683c1c6302]: In what county was Duffy Jackson born?
Gold answer: Nassau County
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Freeport, New York is retrieved, but its Nassau County relation is missing.
====================================================================================================
Q19 [5ae6363b55429929b0807af0]: When was the defending titlist of 2009–10 Biathlon World Cup – Pursuit Men born?
Gold answer: 27 January 1974
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Ole Einar Bjørndalen is identified, but his birth date is not retrieved.
====================================================================================================
Q20 [5a8cea40554299441c6b9f76]: Which mountain is taller, Gasherbrum II or Langtang Ri?
Gold answer: Gasherbrum II
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Gasherbrum II's height is present, but Langtang Ri's height is not, so the comparison is incomplete.
====================================================================================================
Q21 [5ab5ecd75542992aa134a3e6]: Which Dutch media tycoon transferred all of its media activities to Talpa Holding?
Gold answer: John de Mol Jr.
Naive RAG: John de Mol Jr.
CRAG: John de Mol Jr.
Manual verdict: tie_both_good
Why: Both correctly return John de Mol Jr., explicitly identified as the media tycoon behind Talpa Holding.
====================================================================================================
Q22 [5a84c5545542991dd0999dee]: When did the car depicted on the cover of Pentastar: In the Style of Demons cease production?
Gold answer: 1974
Naive RAG: The car depicted on the cover of Pentastar: In the Style of Demons is a Plymouth Barracuda, which ceased production in 1974.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: naive_better
Why: Naive RAG connects the cover car to the Plymouth Barracuda and its 1974 end year; CRAG keeps the end year but drops the cover-to-car bridge.
====================================================================================================
Q23 [5adeacf955429975fa854f66]: What commentator and author questioned the validity of CORE's non-profit status?
Gold answer: Rachel Anne Maddow
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Rachel Maddow and CORE are absent from all retrieved passages.
====================================================================================================
Q24 [5a8ce15d554299653c1aa12f]: did Robert Wise have more award nominations than Zoltan Korda?
Gold answer: yes
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The passages contain neither Robert Wise nor nomination totals; the reference 'yes' cannot be evaluated from this pool and literal short-answer matching is unreliable.
====================================================================================================
Q25 [5ade4da055429939a52fe878]: My Neighbor Totoro was produced by a Japanese animation film studio founded in what year?
Gold answer: 1985
Naive RAG: 1985
CRAG: 1985
Manual verdict: tie_both_good
Why: Both correctly return 1985 from explicit Studio Ghibli founding evidence.
====================================================================================================
Q26 [5ab2a186554299295394677b]: When did the English local newspaper, featuring the sculpture and war memorial in the Forbury gardens, change names?
Gold answer: 2009
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The monument and location are retrieved, but the newspaper and its 2009 name change are not.
====================================================================================================
Q27 [5ade66e1554299728e26c713]: What years did Jose Gonzalo Rodriguez Gacha and other leaders of fthe Medallin Cartel operate in Boliva, Colombia, Central America, Peru, the United States, Canada, and Europe?
Gold answer: 1970s and 1980s
Naive RAG: Based on the evidence provided, the Medellín Cartel, which included José Gonzalo Rodríguez Gacha as a founder and leader, operated in Bolivia, Colombia, Central America, Peru, the United States, Canada, and Europe throughout the **1970s and 1980s**.
CRAG: The Medellín Cartel operated throughout the 1970s and 1980s in Bolivia, Colombia, Central America, Peru, the United States, Canada, and Europe.
Manual verdict: tie_both_good
Why: Both accurately return the 1970s and 1980s from the Medellín Cartel passage.
====================================================================================================
Q28 [5a7c634c55429907fabeef79]: Which writer died later, Agatha Christie or Clement Greenberg?
Gold answer: Clement Greenberg
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Neither writer's death date is retrieved, so the requested comparison is impossible from the evidence.
====================================================================================================
Q29 [5ae13f3c5542997b2ef7d168]: Arthur Noss was a gunner for the commader during which two European theatre battles in WWII?
Gold answer: Battle of Britain and the Battle of Malta
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The retrieved material concerns generic WWII media rather than Arthur Noss or the two battles.
====================================================================================================
Q30 [5ae17cd055429901ffe4aea3]: Between Pinanga and Alopecurus which genus is more common in temperate regions?
Gold answer: Alopecurus
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Neither Pinanga nor Alopecurus is present in the retrieved passages.
====================================================================================================
Q31 [5ae7940c55429952e35ea984]: What is the name of shipping magnate Mærsk Mc-Kinney Møller' father?
Gold answer: A.P. Møller
Naive RAG: A.P. Møller
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: naive_better
Why: Naive RAG correctly connects Mærsk Mc-Kinney Møller to A.P. Møller; CRAG's sentence splitting truncates the decisive name to 'A.P.' and loses the answer.
====================================================================================================
Q32 [5a7296815542991f9a20c515]: Who brewed the first espresso coffee in space, Patrick Baudry or Samantha Cristoforetti?
Gold answer: Samantha Cristoforetti
Naive RAG: Samantha Cristoforetti brewed the first espresso coffee in space.
CRAG: Samantha Cristoforetti brewed the first espresso coffee in space.
Manual verdict: tie_both_good
Why: Both identify Samantha Cristoforetti, but the evidence says she drank the first espresso while the question says brewed; the identity is right despite that wording mismatch.
====================================================================================================
Q33 [5ab2e8ad554299340b525562]: Who starred alongside South Korean actor and singer Kim Ki-bum in the 2012 romantic comedy series I Love Lee Tae-ri?
Gold answer: Park Ye-jin
Naive RAG: Park Ye-jin.
CRAG: Park Ye-jin
Manual verdict: tie_both_good
Why: Both correctly answer Park Ye-jin from the explicit cast sentence.
====================================================================================================
Q34 [5a89b1de5542992e4fca8378]: Which port city lies approximately 25 km north of the Lingnan Fine Arts Museum?
Gold answer: Keelung
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: The retrieved Polish villages are unrelated to the Lingnan museum and Keelung.
====================================================================================================
Q35 [5ab78edc5542995dae37e95c]: Where is the school that Tyler Kalinoski went to located?
Gold answer: located in Olathe, Kansas
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate
Why: Retrieval returns schools containing Tyler in their names, not Tyler Kalinoski's school in Olathe, Kansas.
====================================================================================================
Q36 [5ae73acb5542991e8301cc07]: D1NZ is a series based on what oversteering technique?
Gold answer: Drifting
Naive RAG: I don't have enough information in the provided evidence to answer this question.
CRAG: I don't have enough information in the provided evidence to answer this question.
Manual verdict: tie_both_inadequate